<?php

/**
 * @author holodek
 * @copyright 2009
 */



function retiraCaracteres($string) { // Função para converter caracteres
$arrayRetira = array(   "porra ",
                        "porra, ",
	                    "caralho ",
	                    "caralho, ",
						"cuzão ",
						"cuzão, ",
						"puta ",
						"puta, ",
						"vagabunda ",
						"vagabunda, ",
						"merda ",
						"merda, ",
						"buceta ",
						"buceta, ",
						"cu ",
						"cu, ",
						"vadia ",
						"vadia, ",
						"bosta ",
						"bosta, ",
						"pinto ",
						"pinto, ",
						"verme ",
						"verme, ",
						"noia ",
						"noia, ",
						"safado ",
						"safado, ",
						"pilantra ",
						"pilantra, ",
						"bundao ",
						"bundao, ",
						"viado ",
						"viado, ",
						"bicha ",
						"bicha, ",
						"arrambado ",
						"arrambado, ",
						"ANUS ",
						"ANUS, ",
						"ÁNUS ",
						"ÁNUS, ",
						"BABA-OVO ",
						"BABAOVO ",
						"BABACA ",
						"BACURA ",
						"BAGOS ",
						"BAITOLA ",
						"BEBUM ",
						"BESTA ",
						"BICHA ",
						"BISCA ",
						"BIXA ",
						"BOAZUDA ",
						"BOCETA ",
						"BOCO ",
						"BOCÓ ",
						"BOIOLA ",
						"BOLAGATO ",
						"BOQUETE ",
						"BOLCAT ",
						"BOSSETA ",
						"BOSTA ",
						"BOSTANA ",
						"BRECHA ",
						"BREXA ",
						"BRIOCO ",
						"BRONHA ",
						"BUCA ",
						"BUCETA ",
						"BUNDA ",
						"BUNDUDA ",
						"BURRA ",
						"BURRO ",
						"BUSSETA ",
						"CACHORRA ",
						"CACHORRO ",
						"CADELA ",
						"CAGA ",
						"CAGADO ",
						"CAGAO ",
						"CAGONA ",
						"CANALHA ",
						"CARALHO ",
						"CASSETA ",
						"CASSETE ",
						"CHECHECA ",
						"CHERECA ",
						"CHIBUMBA ",
						"CHIBUMBO ",
						"CHIFRUDA ",
						"CHIFRUDO ",
						"CHOTA ",
						"CHOCHOTA ",
						"CHUPADA ",
						"CHUPADO ",
						"CLITORIS ",
						"CLITÓRIS ",
						"COCAINA ",
						"COCAÍNA ",
						"COCO ",
						"COCÔ ",
						"CORNA ",
						"CORNO ",
						"CORNUDA ",
						"CORNUDO ",
						"CORRUPTA ",
						"CORRUPTO ",
						"CRETINA ",
						"CRETINO ",
						"CRUZ-CREDO ",
						"CU ",
						"CÚ ",
						"CULHAO ",
						"CULHÃO ",
						"CULHÕES ",
						"CURALHO ",
						"CUZAO ",
						"CUZÃO ",
						"CUZUDA ",
						"CUZUDO ",
						"DEBIL ",
						"DEBILOIDE ",
						"DEFUNTO ",
						"DEMONIO ",
						"DEMÔNIO ",
						"DIFUNTO ",
						"DOIDA ",
						"DOIDO ",
						"EGUA ",
						"ÉGUA ",
						"ESCROTA ",
						"ESCROTO ",
						"ESPORRADA ",
						"ESPORRADO ",
						"ESPORRO ",
						"ESPÓRRO ",
						"ESTUPIDA ",
						"ESTÚPIDA ",
						"ESTUPIDEZ ",
						"ESTUPIDO ",
						"ESTÚPIDO ",
						"FEDIDA ",
						"FEDIDO ",
						"FEDOR ",
						"FEDORENTA ",
						"FEIA ",
						"FEIO ",
						"FEIOSA ",
						"FEIOSO ",
						"FEIOZA ",
						"FEIOZO ",
						"FELACAO ",
						"FELAÇÃO ",
						"FENDA ",
						"FODA ",
						"FODAO ",
						"FODÃO ",
						"FODE ",
						"FODIDA ",
						"FODIDO ",
						"FORNICA ",
						"FUDENDO ",
						"TETUDA ",
						"Tesão ", 
						"Tosco ", 
						"Tragado ", 
						"Tapado ", 
						"Rapariga ", 
						"Rampero ", 
						"Rusguento ", 
						"Porra ", 
						"Pinto ", 
						"Puta ", 
						"Puta ",
						"merda ", 
						"Pederasta ", 
						"Pau no teu cu ", 
						"Preguiçoso ", 
						"Pança ",
						"Viado ",
						"nadegas ", 
						"Noia ", 
						"Jumento ", 
						"Jegue ", 
						"Inascível ", 
						"Idiota ", 
						"Imundo ", 
						"Homossexual ", 
						"Herege ",
						"Gay ", 
						"Ricardão ", 
						"gozado ", 
						"Ogro ", 
						"Fiofó ", 
						"Foda ", 
						"Fuder ", 
						"Fudido ", 
						"Fella da Puta ", 
						"Falso ", 
						"Feio ", 
						"Erudito ", 
						"Escroto ", 
						"Estúpido ", 
						"Exdrúxulo ", 
						"Esporrado ", 
						"Desgraçado ", 
						"cú ", 
						"merda ", 
						"buceta ",
						"arrombada ", 
						"Caralho ", 
						"Cacete ", 
						"Cu ", 
						"Catso ", 
						"Cazzo ", 
						"Corno ", 
						"Capeta ", 
						"caralho ", 
						"Bosta ", 
						"Buceta ", 
						"Bicha ", 
						"Babaca ", 
						"Boca-de-burro ", 
						"Burro ", 
						"Bundão ", 
						"Bobo ", 
						"Boçal ", 
						"Esperma ", 
						"Baleia ", 
						"Barril ", 
						"Arrombado ",
						"gozo ",
						"pó ", 
						"Alienado ", 
						"arrobado ",
						"espirante ",
						"piriguete ",
						"piriguetes ",
						"PIRIGUETE ",
						"Filha da Puta ",
						"Filhas da Puta ",
						"vaca ",
						"foder ",
						"cabroes ",
						"xupam ",
						"pintelhos ",
						"pentelhos ",
						"diabo ",
						"diabo, ",
						"peste ",
						"praga ",
						"peste ",
						"arrombados ",
						"bucetuda ",
						"capeta ",
						"filhos do diabo ",
						"arrombado ",
						"arrombado, ",
						"safada ",
						"safada, ",
						"pario ");
						
for($i = 0; $i < count($arrayRetira); $i++){
$string = ereg_replace(strtolower(retirar_carac($arrayRetira[$i])),"<img src='../graphics/c-angry.png' width=50 height=20>",strtolower($string));

}
return $string;
}

$database =	$db;     // Banco de Dados


function encode_msg ($smil) {
    global $image_dir,$database;
    if ($smil) {
        $smil = str_replace("\r", "", $smil);             // Replace carrige return
        $smil = str_replace("\n", "<BR>", $smil); 	// Replace newline with <br>
	$result = mysql_db_query($database, "SELECT * FROM smilies") or died("Query Error");
        while ($db = mysql_fetch_array($result)) {
	    $smil = str_replace($db[code], "<img src=".$image_dir."../graphics/smilies/".$db[file].">", $smil); // Smilie
        }
    }
    return $smil;
}

Function retirar_carac($var){

$var = ereg_replace("[ÁÀÂ]",        "A",$var);
$var = ereg_replace("[áàâª]",       "a",$var);
$var = ereg_replace("[ÉÈÊ]",         "E",$var);
$var = ereg_replace("[éèê]",         "e",$var);
$var = ereg_replace("[ÓÒÔÕ]",        "O",$var);
$var = ereg_replace("[óòôõº]",       "o",$var);
$var = ereg_replace("[ÚÙÛ]",         "U",$var);
$var = ereg_replace("[úùû]",         "u",$var);
$var = ereg_replace("[*#'´`!$%¨]",  " ",$var);
$var = str_replace("\\",             " ",$var);
$var = str_replace(" or ",           " ",$var);
$var = str_replace("select ",        " ",$var);
$var = str_replace("delete ",        " ",$var);
$var = str_replace("create ",        " ",$var);
$var = str_replace("drop ",          " ",$var);
$var = str_replace("update ",        " ",$var);
$var = str_replace("drop table",     " ",$var);
$var = str_replace("show table",     " ",$var);
$var = str_replace("applet",         " ",$var);
$var = str_replace("objetc",         " ",$var);
$var = str_replace("where",          " ",$var);

return($var);
}

?>